services:
  question-service:
    build:
      context: ./Backend/QuestionService
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  user-service:
    build:
      context: ./Backend/user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  matching-service:
    build:
      context: ./Backend/MatchingService
      dockerfile: Dockerfile
    ports:
      - "3003:3003"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
