services:
  question-service:
    build:
      context: ./Backend/QuestionService
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  user-service:
    build:
      context: ./Backend/user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  matching-service:
    build:
      context: ./Backend/MatchingService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  collab-service:
    build:
      context: ./Backend/CollabService
      dockerfile: Dockerfile
    ports:
      - "3004:3004" # change the first port number xxxx:3004 to suit your needs
      - "1234:1234"
  
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
